### ISSUE TITLE
What do you mean by comparing with Vala?

### ISSUE THREAD

**Issue by gavr123456789** [aeldemery/d_sinewave#1]

**Comment by aeldemery** [comment]
I'm not a programmer. Programming is just my hobby. I wanted to compare ease of Gtk App development using Dlang vs Vala. I found myself more happy with Vala although I like both.

**Comment by gavr123456789** [comment]
Heh, absolutely the same. I like D, Nim, but Vala most of all for its simplicity, speed (ARC), and the ability to use from other scripting languages.
